/*
 * Generated by MTK SP DrvGen Version 10.03.0 for MT6589_NP. Copyright MediaTek Inc. (C) 2012.
 * Sat Aug 24 23:46:51 2019
 * Do Not Modify the File.
 */



#include "pmic_drv.h"




//For PMIC driver use


