/*
 * Generated by MTK SP DrvGen Version 10.03.0 for MT6589_NP. Copyright MediaTek Inc. (C) 2012.
 * Sat Sep 14 19:13:39 2019
 * Do Not Modify the File.
 */



#include "pmic_drv.h"




//For PMIC driver use
void pmic_init(void) {
}



